version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
  web:
    build: .
    image: app
    command: python3 manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
