# Generated by Django 2.1.2 on 2018-12-19 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fontawesome.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='JavascriptDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('nbcomponents', models.IntegerField(default='0')),
                ('theorical_result', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='JavascriptDrawSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawtype', models.CharField(choices=[('s', 'Square'), ('e', 'Ellipse'), ('r', 'RegularPolygon'), ('st', 'Star'), ('p', 'Polyline')], default='s', max_length=6)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('linewidth', models.FloatField(default=0.0)),
                ('angle1', models.IntegerField(default=0)),
                ('angle2', models.IntegerField(default=360)),
                ('side', models.IntegerField(default=6)),
                ('fill', models.CharField(default='FFFFFF', max_length=6)),
                ('stroke', models.CharField(default='FFFFFF', max_length=6)),
                ('closing', models.BooleanField(default=True)),
                ('nbpoints', models.IntegerField(default=0.0)),
                ('innerradius', models.FloatField(default=0.0)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('node_id', models.IntegerField(default=0)),
                ('node_style', models.TextField(default='circ')),
                ('node_custom_name', models.TextField(default='')),
                ('node_initial', models.BooleanField(default=True)),
                ('node_final', models.BooleanField(default=True)),
                ('trans_id', models.IntegerField(default=0)),
                ('trans_node_1', models.TextField(default='')),
                ('trans_node_2', models.TextField(default='')),
                ('trans_x1', models.IntegerField(default=0)),
                ('trans_x2', models.IntegerField(default=0)),
                ('trans_y1', models.IntegerField(default=0)),
                ('trans_y2', models.IntegerField(default=0)),
                ('trans_custom_name', models.TextField(default='')),
                ('trans_style', models.IntegerField(default=0)),
                ('javascriptdraw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JavascriptDraw')),
            ],
        ),
        migrations.CreateModel(
            name='LatexDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('visibility', models.CharField(choices=[('pub', 'Public'), ('pri', 'Private')], default='pri', max_length=3)),
                ('content', models.TextField(default='')),
                ('creat_date', models.DateTimeField(verbose_name='date creation')),
                ('latex_type', models.CharField(choices=[('arc', 'Arc'), ('arr', 'Arrow'), ('cir', 'Circle'), ('dia', 'Diamond'), ('ell', 'Ellipse'), ('gra', 'Graph'), ('lin', 'Line'), ('mol', 'Molecule'), ('par', 'Parallelogram'), ('pol', 'Polygon'), ('rec', 'Rectangle'), ('sta', 'Star'), ('tra', 'Trapeze'), ('tre', 'Tree'), ('tri', 'Triangle'), ('com', 'Complexe')], max_length=50)),
                ('creation_type', models.CharField(choices=[('c', 'Converte'), ('g', 'Generate'), ('d', 'Draw')], max_length=50)),
                ('message_count', models.IntegerField(default=0)),
                ('good', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('creat_date', models.DateTimeField(verbose_name='date creation')),
            ],
        ),
        migrations.CreateModel(
            name='PersoLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[('1', 1), ('-1', -1)], default='1')),
                ('creat_date', models.DateTimeField(verbose_name='date creation')),
                ('latexdoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LatexDoc')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(default='avatar.png')),
                ('moto', models.TextField(blank=True, max_length=500)),
                ('news_wanted', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('fr', 'French'), ('eng', 'English')], default='en', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200)),
                ('color', models.CharField(default='FFFFFF', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latexdoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LatexDoc')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserSecretLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_link', models.CharField(max_length=200)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XYList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('javascriptdrawspecs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JavascriptDrawSpecs')),
            ],
        ),
        migrations.AddField(
            model_name='javascriptdraw',
            name='latexdoc',
            field=models.ForeignKey(default=114, on_delete=django.db.models.deletion.CASCADE, to='app.LatexDoc'),
        ),
        migrations.AddField(
            model_name='download',
            name='latexdoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LatexDoc'),
        ),
        migrations.AddField(
            model_name='download',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='latexdoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LatexDoc'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
